global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:18080"]
  - job_name: "alphaid"
    static_configs:
      - targets: ["alphaid:8000"]
  - job_name: "nebula"
    static_configs:
      - targets: ["nebula:2002"]
  - job_name: "orchestrator"
    static_configs:
      - targets: ["orchestrator:19090"]
